qsub job_set1.sh
qsub job_set2.sh
qsub job_set3.sh
qsub job_set4.sh
qsub job_set5.sh
qsub job_set6.sh
qsub job_set7.sh
qsub job_set8.sh
qsub job_set9.sh
qsub job_set10.sh
qsub job_set11.sh
qsub job_set12.sh